layout_spectrum: 1
typography_spectrum: 0.2455197
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.516129
  brandColors:
    - '#000000'
    - '#B4B4B4'
    - '#2C2C2C'
    - '#585858'
    - '#8A8A8A'
  rhythmicContrast: 1
name: musicinhands
